import type { ExpenseTarget } from '@/types';

export const EXPECTED_HEADERS = [
    'year', 'month', 'date', 'target', 'category', 'value',
    'item', 'context', 'method', 'shop', 'location'
];

export const HEADER_ALIASES: Record<string, string> = {
    'detail': 'item',
    'description': 'item',
    'expense': 'item',
    'payment': 'method',
    'payment_method': 'method',
    'paymentmethod': 'method',
    'store': 'shop',
    'vendor': 'shop',
    'merchant': 'shop',
    'place': 'location',
    'area': 'location',
    'city': 'location',
    'amount': 'value',
    'price': 'value',
    'cost': 'value',
    'bucket': 'target',
    'goal': 'target',
    'type': 'category',
    'note': 'context',
    'notes': 'context',
    'reason': 'context',
};

export const TARGET_MAPPING: Record<string, ExpenseTarget> = {
    'living': 'Living',
    'present': 'Present',
    'future': 'Future',
    'saving': 'Future',
    'savings': 'Future',
    'investment': 'Future',
    'investments': 'Future',
    'save': 'Future',
    'invest': 'Future',
};

export const CATEGORY_NORMALIZATION: Record<string, string> = {
    'transportation': 'Transport',
    'transport': 'Transport',
    'transit': 'Transport',
    'travel & experiences': 'Travel & Experiences',
    'travel': 'Travel & Experiences',
    'hobbies & leisure': 'Hobbies & Leisure',
    'hobbies': 'Hobbies & Leisure',
    'leisure': 'Hobbies & Leisure',
    'entertainment': 'Enjoyment & Social Life',
    'social': 'Enjoyment & Social Life',
    'enjoyment & social life': 'Enjoyment & Social Life',
    'enjoyment': 'Enjoyment & Social Life',
    'utilities & services': 'Utilities & Services',
    'utilities': 'Utilities & Services',
    'services': 'Utilities & Services',
    'basic personal care': 'Basic Personal Care',
    'personal care': 'Basic Personal Care',
    'healthcare': 'Basic Personal Care',
    'health': 'Basic Personal Care',
    'subscriptions': 'Subscriptions',
    'subscription': 'Subscriptions',
    'food': 'Food',
    'groceries': 'Food',
    'dining': 'Food',
    'restaurants': 'Food',
    'clothing': 'Clothing',
    'clothes': 'Clothing',
    'apparel': 'Clothing',
    'fashion': 'Clothing',
    'housing': 'Housing',
    'rent': 'Housing',
    'home': 'Housing',
    '"life happens" fund': '"Life Happens" Fund',
    'life happens fund': '"Life Happens" Fund',
    'emergency': '"Life Happens" Fund',
    'emergency fund': '"Life Happens" Fund',
};
